export const ADD_CARD = 'ADD_CARD';
export const ADD_DECK = 'ADD_DECK';
export const DELETE_DECK = 'DELETE_DECK';
export const FETCH_DECKS_REQUEST = 'FETCH_DECKS_REQUEST';
export const FETCH_DECKS_SUCCESS = 'FETCH_DECKS_SUCCESS';
